### ISSUE TITLE
Problem with if statement evaluation

### ISSUE THREAD

**Issue by OliJimbo** [sdparsons/splithalf#1]
When running an accuracy only split half, the following message is returned:

```
Error in splithalf(data = dat, outcome = "accuracy", var.participant = "id",  : 
  the RT varible has not been specified
```

**Comment by sdparsons** [comment]
This should have been fixed in the most recent version

**Comment by sdparsons** [comment]
Thanks for the comment, as far as I can tell from my testing this has been fixed in a recent update.
