### ISSUE TITLE
Enhance documentation for exported functions 

### ISSUE THREAD

**Issue by rMassimiliano** [sdparsons/splithalf#10]
In the help for the functions `multiverse.plot`, `threshold`, `splithalf.multiverse`,`testretest.multiverse`, the `Description` section is missing.

Also, consider adding a simple working examples in the `Examples` sections of the documentation, or at the very least a link to the specific section of the "online documentation" 

In my opinion all exported functions should have a clear documentation.

https://github.com/openjournals/joss-reviews/issues/3041

**Comment by sdparsons** [comment]
thanks @rMassimiliano! 
As an interim update - I've done this for the functions splithalf, splithalf_multiverse, threshold, and plot_multiverse. 
I am working to improve the flexibility of the testretest_multiverse function, and will add the documentation and examples for this asap too

**Comment by sdparsons** [comment]
Hey @rMassimiliano I have now added documentation help for the testretest.multiverse function and included the multiverse functions in the validation sim in the vignettes.
