### ISSUE TITLE
Validation of estimates

### ISSUE THREAD

**Issue by Nathaniel-Haines** [sdparsons/splithalf#9]
Hi @sdparsons, I am wondering if you have run any validation analyses to ensure that the estimates you are getting for splithalf results are what you expect? I checked the psych methods paper that you reference in the documentation, but was not able to find anything specifically on validating the software. 

For validation, I am referring something like simulating with a known reliability and using `splithalf::splithalf` to recover it, or alternatively comparing the output of `splithalf::splithalf` to other packages. For the latter case, I wrote up some code to compare `splithalf::splithalf` to `psych::splitHalf`, which offers similar functionality. As you will see from the `R` code and corresponding distributions of estimates below, they do return similar results for one simple example, although they are not identical. I wonder if it would be worth doing a more comprehensive comparison for validation (e.g., as in the splithalfr package described here: https://github.com/tpronk/splithalfr_simulation).

Here is the code I used to run a simple validation check, along with a plot of the distribution of estimates at the end:

`# compare with other package results
library(splithalf)
library(psych)
library(tidyr)
library(dplyr)
library(patchwork)

# Simulate data
set.seed(43201)
n_participants <- 60 ## sample size
n_trials <- 80
n_blocks <- 2
sim_data <- data.frame(participant_number = rep(1:n_participants, each = n_blocks * n_trials),
                       trial_number = rep(1:n_trials, times = n_blocks * n_participants),
                       block_name = rep(c("A","B"), each = n_trials, length.out = n_participants * n_trials * n_blocks),
                       trial_type = rep(c("congruent","incongruent"), length.out = n_participants * n_trials * n_blocks),
                       RT = rnorm(n_participants * n_trials * n_blocks, 500, 200),
                       ACC = 1)

# create wide data for psych::SplitHalf
test_dat <- sim_data %>%
  filter(trial_type=="congruent" & block_name=="A") %>%
  select(participant_number, trial_number, RT) %>%
  pivot_wider(names_from = trial_number, 
              values_from = RT, 
              names_prefix = "T") %>%
  select(-participant_number)

# splithalf::splithalf output
splithalf_res <- sim_data %>%
  filter(trial_type=="congruent" & block_name=="A") %>%
  splithalf(data = .,
            outcome = "RT",
            score = "average",
            conditionlist = c("A"),
            halftype = "random",
            permutations = 5000,
            var.RT = "RT",
            var.condition = "block_name",
            var.participant = "participant_number",
            var.compare = "trial_type",
            average = "mean",
            plot = TRUE)

# psych::SplitHalf output
psych_res <- splitHalf(test_dat, n.sample = 5000, check.keys = F, raw = T)
psych_res

# compare psych to splithalf reseults
p1 <- qplot(psych_res$raw, 
            main = "psych\nraw values", 
            xlim = c(-.6, .6),
            ylim = c(0, 900),
            xlab = "") 
p2 <- qplot(splithalf_res$estimates$spearmanbrown,
            main = "splithalf\nSpearman-Brown",
            xlim = c(-.6, .6),
            ylim = c(0, 900),
            xlab = "Split-Half Reliability")
p3 <- qplot(splithalf_res$estimates$splithalf, 
            main = "splithalf\nuncorrected",
            xlim = c(-.6, .6),
            ylim = c(0, 900),
            xlab = "")

p1 | p2 | p3`

![plot_zoom_png](https://user-images.githubusercontent.com/25613611/110004906-ecf89080-7ce5-11eb-9b8f-3c9a6f66f1c1.png)

**Comment by sdparsons** [comment]
Thanks @Nathaniel-Haines !
I can certainly look further into simulating to validate the functions. Especially with known (non 0) reliability. Thanks for such a useful starting point!

**Comment by sdparsons** [comment]
I have added a validation script to the vignettes (https://github.com/sdparsons/splithalf/tree/master/vignettes). This was a really useful exercise as I was able to catch several minor bugs with some of the combinations. 

Currently the main use is to check that the function works, rather than speaking entirely to the validation point - but it's a step in the right direction :)

It currently runs all combinations of the following options: outcome x score x halftype x average = 2x3x3x2 = 36

* outcome = "RT"
* outcome = "accuracy"

* score = "average"
* score = "difference" (the default option)
* score = "difference_of_difference"

* halftype = "oddeven"
* halftype = "halfs"
* halftype = "random"

* average = "mean"
* average = "median"

**Comment by Nathaniel-Haines** [comment]
I am happy the tests were helpful! I agree on this being a step in the right direction. 

Do you plan on adding a parameter recovery type of validation, or do you think these checks are sufficient for now? (I just want to make sure I am not holding this open if we think the current checks are reasonable for now)

**Comment by sdparsons** [comment]
What I'd really like to do is figure out how to simulate data with specified reliabilities in order to test parameter recovery. I've not had enough of a chance to look into this for difference scores in particular - and for internal consistency, rather than test retest. 
Leave it with me for now :)

**Comment by sdparsons** [comment]
On reflection from the twitter conversation about this, I suspect that a full parameter recovery simulation might be big enough to almost constitute a separate project. So, for now I think that aspect of this issue could be closed. 

What I will still do is build a vignette to check that all of the multiverse options and related functions work across input parameters.

**Comment by Nathaniel-Haines** [comment]
Yes that is what I was beginning to worry about upon thinking of this further! That said, I think we can consider this closed, and I can wrap up my end of the review 😄
